; Auto-generated. Do not edit!


(cl:in-package smach_-msg)


;//! \htmlinclude sinkGoal.msg.html

(cl:defclass <sinkGoal> (roslisp-msg-protocol:ros-message)
  ((depth
    :reader depth
    :initarg :depth
    :type cl:integer
    :initform 0))
)

(cl:defclass sinkGoal (<sinkGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <sinkGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'sinkGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name smach_-msg:<sinkGoal> is deprecated: use smach_-msg:sinkGoal instead.")))

(cl:ensure-generic-function 'depth-val :lambda-list '(m))
(cl:defmethod depth-val ((m <sinkGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader smach_-msg:depth-val is deprecated.  Use smach_-msg:depth instead.")
  (depth m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <sinkGoal>) ostream)
  "Serializes a message object of type '<sinkGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'depth)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'depth)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'depth)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'depth)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <sinkGoal>) istream)
  "Deserializes a message object of type '<sinkGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'depth)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'depth)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'depth)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'depth)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<sinkGoal>)))
  "Returns string type for a message object of type '<sinkGoal>"
  "smach_/sinkGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'sinkGoal)))
  "Returns string type for a message object of type 'sinkGoal"
  "smach_/sinkGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<sinkGoal>)))
  "Returns md5sum for a message object of type '<sinkGoal>"
  "4fb87ef1559454daf6f1b01af71125ad")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'sinkGoal)))
  "Returns md5sum for a message object of type 'sinkGoal"
  "4fb87ef1559454daf6f1b01af71125ad")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<sinkGoal>)))
  "Returns full string definition for message of type '<sinkGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 depth~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'sinkGoal)))
  "Returns full string definition for message of type 'sinkGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 depth~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <sinkGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <sinkGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'sinkGoal
    (cl:cons ':depth (depth msg))
))
