(cl:in-package srmauv_msgs-msg)
(cl:export '(ENABLE-VAL
          ENABLE
          TUNE-VAL
          TUNE
          TORPEDO-VAL
          TORPEDO
          DROPPER-VAL
          DROPPER
          DEPTH_ENABLE-VAL
          DEPTH_ENABLE
          PID_ENABLE-VAL
          PID_ENABLE
          FORWARD_SPEED-VAL
          FORWARD_SPEED
          SIDEMOVE_SPEED-VAL
          SIDEMOVE_SPEED
          REVERSE_SPEED-VAL
          REVERSE_SPEED
          DEPTH_SETPOINT-VAL
          DEPTH_SETPOINT
          HEADING_SETPOINT-VAL
          HEADING_SETPOINT
          ROLL_SETPOINT-VAL
          ROLL_SETPOINT
          PITCH_SETPOINT-VAL
          PITCH_SETPOINT
          SIDEMOVE_INPUT-VAL
          SIDEMOVE_INPUT
          FORWARD_INPUT-VAL
          FORWARD_INPUT
))