// Generated by gencpp from file smach_/sinkGoal.msg
// DO NOT EDIT!


#ifndef SMACH__MESSAGE_SINKGOAL_H
#define SMACH__MESSAGE_SINKGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smach_
{
template <class ContainerAllocator>
struct sinkGoal_
{
  typedef sinkGoal_<ContainerAllocator> Type;

  sinkGoal_()
    : depth(0)  {
    }
  sinkGoal_(const ContainerAllocator& _alloc)
    : depth(0)  {
  (void)_alloc;
    }



   typedef uint32_t _depth_type;
  _depth_type depth;




  typedef boost::shared_ptr< ::smach_::sinkGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smach_::sinkGoal_<ContainerAllocator> const> ConstPtr;

}; // struct sinkGoal_

typedef ::smach_::sinkGoal_<std::allocator<void> > sinkGoal;

typedef boost::shared_ptr< ::smach_::sinkGoal > sinkGoalPtr;
typedef boost::shared_ptr< ::smach_::sinkGoal const> sinkGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smach_::sinkGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smach_::sinkGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace smach_

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'smach_': ['/home/parth/sedna/devel/share/smach_/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::smach_::sinkGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smach_::sinkGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smach_::sinkGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smach_::sinkGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smach_::sinkGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smach_::sinkGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smach_::sinkGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fb87ef1559454daf6f1b01af71125ad";
  }

  static const char* value(const ::smach_::sinkGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fb87ef1559454daULL;
  static const uint64_t static_value2 = 0xf6f1b01af71125adULL;
};

template<class ContainerAllocator>
struct DataType< ::smach_::sinkGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smach_/sinkGoal";
  }

  static const char* value(const ::smach_::sinkGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smach_::sinkGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
uint32 depth\n\
";
  }

  static const char* value(const ::smach_::sinkGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smach_::sinkGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.depth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct sinkGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smach_::sinkGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smach_::sinkGoal_<ContainerAllocator>& v)
  {
    s << indent << "depth: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.depth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMACH__MESSAGE_SINKGOAL_H
