// Generated by gencpp from file srmauv_msgs/buoy.msg
// DO NOT EDIT!


#ifndef SRMAUV_MSGS_MESSAGE_BUOY_H
#define SRMAUV_MSGS_MESSAGE_BUOY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srmauv_msgs
{
template <class ContainerAllocator>
struct buoy_
{
  typedef buoy_<ContainerAllocator> Type;

  buoy_()
    : possible_red(false)
    , possible_green(false)
    , x_offset_green(0.0)
    , y_offset_green(0.0)
    , x_offset_red(0.0)
    , y_offset_red(0.0)  {
    }
  buoy_(const ContainerAllocator& _alloc)
    : possible_red(false)
    , possible_green(false)
    , x_offset_green(0.0)
    , y_offset_green(0.0)
    , x_offset_red(0.0)
    , y_offset_red(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _possible_red_type;
  _possible_red_type possible_red;

   typedef uint8_t _possible_green_type;
  _possible_green_type possible_green;

   typedef float _x_offset_green_type;
  _x_offset_green_type x_offset_green;

   typedef float _y_offset_green_type;
  _y_offset_green_type y_offset_green;

   typedef float _x_offset_red_type;
  _x_offset_red_type x_offset_red;

   typedef float _y_offset_red_type;
  _y_offset_red_type y_offset_red;




  typedef boost::shared_ptr< ::srmauv_msgs::buoy_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srmauv_msgs::buoy_<ContainerAllocator> const> ConstPtr;

}; // struct buoy_

typedef ::srmauv_msgs::buoy_<std::allocator<void> > buoy;

typedef boost::shared_ptr< ::srmauv_msgs::buoy > buoyPtr;
typedef boost::shared_ptr< ::srmauv_msgs::buoy const> buoyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srmauv_msgs::buoy_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srmauv_msgs::buoy_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace srmauv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'srmauv_msgs': ['/home/parth/sedna/src/srmauv_msgs/msg', '/home/parth/sedna/devel/share/srmauv_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::srmauv_msgs::buoy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srmauv_msgs::buoy_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srmauv_msgs::buoy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srmauv_msgs::buoy_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srmauv_msgs::buoy_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srmauv_msgs::buoy_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srmauv_msgs::buoy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32326659a962285da2405f27fc182109";
  }

  static const char* value(const ::srmauv_msgs::buoy_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32326659a962285dULL;
  static const uint64_t static_value2 = 0xa2405f27fc182109ULL;
};

template<class ContainerAllocator>
struct DataType< ::srmauv_msgs::buoy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srmauv_msgs/buoy";
  }

  static const char* value(const ::srmauv_msgs::buoy_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srmauv_msgs::buoy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool possible_red\n\
bool possible_green\n\
float32 x_offset_green\n\
float32 y_offset_green\n\
float32 x_offset_red\n\
float32 y_offset_red\n\
";
  }

  static const char* value(const ::srmauv_msgs::buoy_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srmauv_msgs::buoy_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.possible_red);
      stream.next(m.possible_green);
      stream.next(m.x_offset_green);
      stream.next(m.y_offset_green);
      stream.next(m.x_offset_red);
      stream.next(m.y_offset_red);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct buoy_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srmauv_msgs::buoy_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srmauv_msgs::buoy_<ContainerAllocator>& v)
  {
    s << indent << "possible_red: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.possible_red);
    s << indent << "possible_green: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.possible_green);
    s << indent << "x_offset_green: ";
    Printer<float>::stream(s, indent + "  ", v.x_offset_green);
    s << indent << "y_offset_green: ";
    Printer<float>::stream(s, indent + "  ", v.y_offset_green);
    s << indent << "x_offset_red: ";
    Printer<float>::stream(s, indent + "  ", v.x_offset_red);
    s << indent << "y_offset_red: ";
    Printer<float>::stream(s, indent + "  ", v.y_offset_red);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRMAUV_MSGS_MESSAGE_BUOY_H
