// Generated by gencpp from file srmauv_msgs/c0ntrol.msg
// DO NOT EDIT!


#ifndef SRMAUV_MSGS_MESSAGE_C0NTROL_H
#define SRMAUV_MSGS_MESSAGE_C0NTROL_H

#include <ros/service_traits.h>


#include <srmauv_msgs/c0ntrolRequest.h>
#include <srmauv_msgs/c0ntrolResponse.h>


namespace srmauv_msgs
{

struct c0ntrol
{

typedef c0ntrolRequest Request;
typedef c0ntrolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct c0ntrol
} // namespace srmauv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srmauv_msgs::c0ntrol > {
  static const char* value()
  {
    return "10cf23b8a69d089d84775c51f8c713a7";
  }

  static const char* value(const ::srmauv_msgs::c0ntrol&) { return value(); }
};

template<>
struct DataType< ::srmauv_msgs::c0ntrol > {
  static const char* value()
  {
    return "srmauv_msgs/c0ntrol";
  }

  static const char* value(const ::srmauv_msgs::c0ntrol&) { return value(); }
};


// service_traits::MD5Sum< ::srmauv_msgs::c0ntrolRequest> should match 
// service_traits::MD5Sum< ::srmauv_msgs::c0ntrol > 
template<>
struct MD5Sum< ::srmauv_msgs::c0ntrolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srmauv_msgs::c0ntrol >::value();
  }
  static const char* value(const ::srmauv_msgs::c0ntrolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srmauv_msgs::c0ntrolRequest> should match 
// service_traits::DataType< ::srmauv_msgs::c0ntrol > 
template<>
struct DataType< ::srmauv_msgs::c0ntrolRequest>
{
  static const char* value()
  {
    return DataType< ::srmauv_msgs::c0ntrol >::value();
  }
  static const char* value(const ::srmauv_msgs::c0ntrolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srmauv_msgs::c0ntrolResponse> should match 
// service_traits::MD5Sum< ::srmauv_msgs::c0ntrol > 
template<>
struct MD5Sum< ::srmauv_msgs::c0ntrolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srmauv_msgs::c0ntrol >::value();
  }
  static const char* value(const ::srmauv_msgs::c0ntrolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srmauv_msgs::c0ntrolResponse> should match 
// service_traits::DataType< ::srmauv_msgs::c0ntrol > 
template<>
struct DataType< ::srmauv_msgs::c0ntrolResponse>
{
  static const char* value()
  {
    return DataType< ::srmauv_msgs::c0ntrol >::value();
  }
  static const char* value(const ::srmauv_msgs::c0ntrolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRMAUV_MSGS_MESSAGE_C0NTROL_H
