// Generated by gencpp from file srmauv_msgs/control_mode.msg
// DO NOT EDIT!


#ifndef SRMAUV_MSGS_MESSAGE_CONTROL_MODE_H
#define SRMAUV_MSGS_MESSAGE_CONTROL_MODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srmauv_msgs
{
template <class ContainerAllocator>
struct control_mode_
{
  typedef control_mode_<ContainerAllocator> Type;

  control_mode_()
    : mode(0)
    , setpoint(0.0)
    , value(0.0)  {
    }
  control_mode_(const ContainerAllocator& _alloc)
    : mode(0)
    , setpoint(0.0)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _mode_type;
  _mode_type mode;

   typedef float _setpoint_type;
  _setpoint_type setpoint;

   typedef float _value_type;
  _value_type value;




  typedef boost::shared_ptr< ::srmauv_msgs::control_mode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srmauv_msgs::control_mode_<ContainerAllocator> const> ConstPtr;

}; // struct control_mode_

typedef ::srmauv_msgs::control_mode_<std::allocator<void> > control_mode;

typedef boost::shared_ptr< ::srmauv_msgs::control_mode > control_modePtr;
typedef boost::shared_ptr< ::srmauv_msgs::control_mode const> control_modeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srmauv_msgs::control_mode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srmauv_msgs::control_mode_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace srmauv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'srmauv_msgs': ['/home/parth/sedna/src/srmauv_msgs/msg', '/home/parth/sedna/devel/share/srmauv_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::srmauv_msgs::control_mode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srmauv_msgs::control_mode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srmauv_msgs::control_mode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srmauv_msgs::control_mode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srmauv_msgs::control_mode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srmauv_msgs::control_mode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srmauv_msgs::control_mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3ee509ab57566647d60731902712479";
  }

  static const char* value(const ::srmauv_msgs::control_mode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3ee509ab5756664ULL;
  static const uint64_t static_value2 = 0x7d60731902712479ULL;
};

template<class ContainerAllocator>
struct DataType< ::srmauv_msgs::control_mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srmauv_msgs/control_mode";
  }

  static const char* value(const ::srmauv_msgs::control_mode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srmauv_msgs::control_mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 mode\n\
float32 setpoint\n\
float32 value\n\
";
  }

  static const char* value(const ::srmauv_msgs::control_mode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srmauv_msgs::control_mode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.setpoint);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct control_mode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srmauv_msgs::control_mode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srmauv_msgs::control_mode_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mode);
    s << indent << "setpoint: ";
    Printer<float>::stream(s, indent + "  ", v.setpoint);
    s << indent << "value: ";
    Printer<float>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRMAUV_MSGS_MESSAGE_CONTROL_MODE_H
