// Generated by gencpp from file srmauv_msgs/ControllerResult.msg
// DO NOT EDIT!


#ifndef SRMAUV_MSGS_MESSAGE_CONTROLLERRESULT_H
#define SRMAUV_MSGS_MESSAGE_CONTROLLERRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srmauv_msgs
{
template <class ContainerAllocator>
struct ControllerResult_
{
  typedef ControllerResult_<ContainerAllocator> Type;

  ControllerResult_()
    : heading_final(0.0)
    , forward_final(0.0)
    , sidemove_final(0.0)
    , depth_final(0.0)  {
    }
  ControllerResult_(const ContainerAllocator& _alloc)
    : heading_final(0.0)
    , forward_final(0.0)
    , sidemove_final(0.0)
    , depth_final(0.0)  {
  (void)_alloc;
    }



   typedef float _heading_final_type;
  _heading_final_type heading_final;

   typedef float _forward_final_type;
  _forward_final_type forward_final;

   typedef float _sidemove_final_type;
  _sidemove_final_type sidemove_final;

   typedef float _depth_final_type;
  _depth_final_type depth_final;




  typedef boost::shared_ptr< ::srmauv_msgs::ControllerResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srmauv_msgs::ControllerResult_<ContainerAllocator> const> ConstPtr;

}; // struct ControllerResult_

typedef ::srmauv_msgs::ControllerResult_<std::allocator<void> > ControllerResult;

typedef boost::shared_ptr< ::srmauv_msgs::ControllerResult > ControllerResultPtr;
typedef boost::shared_ptr< ::srmauv_msgs::ControllerResult const> ControllerResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srmauv_msgs::ControllerResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srmauv_msgs::ControllerResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace srmauv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'srmauv_msgs': ['/home/parth/sedna/src/srmauv_msgs/msg', '/home/parth/sedna/devel/share/srmauv_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::srmauv_msgs::ControllerResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srmauv_msgs::ControllerResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srmauv_msgs::ControllerResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srmauv_msgs::ControllerResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srmauv_msgs::ControllerResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srmauv_msgs::ControllerResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srmauv_msgs::ControllerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd1dc8b915dd1c7e428329df44fd5442";
  }

  static const char* value(const ::srmauv_msgs::ControllerResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd1dc8b915dd1c7eULL;
  static const uint64_t static_value2 = 0x428329df44fd5442ULL;
};

template<class ContainerAllocator>
struct DataType< ::srmauv_msgs::ControllerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srmauv_msgs/ControllerResult";
  }

  static const char* value(const ::srmauv_msgs::ControllerResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srmauv_msgs::ControllerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
#result definition\n\
float32 heading_final\n\
float32 forward_final\n\
float32 sidemove_final\n\
float32 depth_final\n\
\n\
";
  }

  static const char* value(const ::srmauv_msgs::ControllerResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srmauv_msgs::ControllerResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.heading_final);
      stream.next(m.forward_final);
      stream.next(m.sidemove_final);
      stream.next(m.depth_final);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ControllerResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srmauv_msgs::ControllerResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srmauv_msgs::ControllerResult_<ContainerAllocator>& v)
  {
    s << indent << "heading_final: ";
    Printer<float>::stream(s, indent + "  ", v.heading_final);
    s << indent << "forward_final: ";
    Printer<float>::stream(s, indent + "  ", v.forward_final);
    s << indent << "sidemove_final: ";
    Printer<float>::stream(s, indent + "  ", v.sidemove_final);
    s << indent << "depth_final: ";
    Printer<float>::stream(s, indent + "  ", v.depth_final);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRMAUV_MSGS_MESSAGE_CONTROLLERRESULT_H
