// Generated by gencpp from file srmauv_msgs/ControllerGoal.msg
// DO NOT EDIT!


#ifndef SRMAUV_MSGS_MESSAGE_CONTROLLERGOAL_H
#define SRMAUV_MSGS_MESSAGE_CONTROLLERGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srmauv_msgs
{
template <class ContainerAllocator>
struct ControllerGoal_
{
  typedef ControllerGoal_<ContainerAllocator> Type;

  ControllerGoal_()
    : heading_setpoint(0.0)
    , forward_setpoint(0.0)
    , sidemove_setpoint(0.0)
    , depth_setpoint(0.0)
    , forward_vel_setpoint(0.0)
    , sidemove_vel_setpoint(0.0)  {
    }
  ControllerGoal_(const ContainerAllocator& _alloc)
    : heading_setpoint(0.0)
    , forward_setpoint(0.0)
    , sidemove_setpoint(0.0)
    , depth_setpoint(0.0)
    , forward_vel_setpoint(0.0)
    , sidemove_vel_setpoint(0.0)  {
  (void)_alloc;
    }



   typedef float _heading_setpoint_type;
  _heading_setpoint_type heading_setpoint;

   typedef float _forward_setpoint_type;
  _forward_setpoint_type forward_setpoint;

   typedef float _sidemove_setpoint_type;
  _sidemove_setpoint_type sidemove_setpoint;

   typedef float _depth_setpoint_type;
  _depth_setpoint_type depth_setpoint;

   typedef float _forward_vel_setpoint_type;
  _forward_vel_setpoint_type forward_vel_setpoint;

   typedef float _sidemove_vel_setpoint_type;
  _sidemove_vel_setpoint_type sidemove_vel_setpoint;




  typedef boost::shared_ptr< ::srmauv_msgs::ControllerGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srmauv_msgs::ControllerGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ControllerGoal_

typedef ::srmauv_msgs::ControllerGoal_<std::allocator<void> > ControllerGoal;

typedef boost::shared_ptr< ::srmauv_msgs::ControllerGoal > ControllerGoalPtr;
typedef boost::shared_ptr< ::srmauv_msgs::ControllerGoal const> ControllerGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srmauv_msgs::ControllerGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srmauv_msgs::ControllerGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace srmauv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'srmauv_msgs': ['/home/parth/sedna/src/srmauv_msgs/msg', '/home/parth/sedna/devel/share/srmauv_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::srmauv_msgs::ControllerGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srmauv_msgs::ControllerGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srmauv_msgs::ControllerGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srmauv_msgs::ControllerGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srmauv_msgs::ControllerGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srmauv_msgs::ControllerGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srmauv_msgs::ControllerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ae442035f67c421602ec8c476fd1372";
  }

  static const char* value(const ::srmauv_msgs::ControllerGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ae442035f67c421ULL;
  static const uint64_t static_value2 = 0x602ec8c476fd1372ULL;
};

template<class ContainerAllocator>
struct DataType< ::srmauv_msgs::ControllerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srmauv_msgs/ControllerGoal";
  }

  static const char* value(const ::srmauv_msgs::ControllerGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srmauv_msgs::ControllerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition \n\
float32 heading_setpoint\n\
float32 forward_setpoint\n\
float32 sidemove_setpoint\n\
float32 depth_setpoint\n\
float32 forward_vel_setpoint\n\
float32 sidemove_vel_setpoint\n\
\n\
";
  }

  static const char* value(const ::srmauv_msgs::ControllerGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srmauv_msgs::ControllerGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.heading_setpoint);
      stream.next(m.forward_setpoint);
      stream.next(m.sidemove_setpoint);
      stream.next(m.depth_setpoint);
      stream.next(m.forward_vel_setpoint);
      stream.next(m.sidemove_vel_setpoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ControllerGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srmauv_msgs::ControllerGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srmauv_msgs::ControllerGoal_<ContainerAllocator>& v)
  {
    s << indent << "heading_setpoint: ";
    Printer<float>::stream(s, indent + "  ", v.heading_setpoint);
    s << indent << "forward_setpoint: ";
    Printer<float>::stream(s, indent + "  ", v.forward_setpoint);
    s << indent << "sidemove_setpoint: ";
    Printer<float>::stream(s, indent + "  ", v.sidemove_setpoint);
    s << indent << "depth_setpoint: ";
    Printer<float>::stream(s, indent + "  ", v.depth_setpoint);
    s << indent << "forward_vel_setpoint: ";
    Printer<float>::stream(s, indent + "  ", v.forward_vel_setpoint);
    s << indent << "sidemove_vel_setpoint: ";
    Printer<float>::stream(s, indent + "  ", v.sidemove_vel_setpoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRMAUV_MSGS_MESSAGE_CONTROLLERGOAL_H
