// Generated by gencpp from file srmauv_msgs/goal.msg
// DO NOT EDIT!


#ifndef SRMAUV_MSGS_MESSAGE_GOAL_H
#define SRMAUV_MSGS_MESSAGE_GOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srmauv_msgs
{
template <class ContainerAllocator>
struct goal_
{
  typedef goal_<ContainerAllocator> Type;

  goal_()
    : goDepth(false)
    , goPitch(false)
    , goRoll(false)
    , goHeading(false)
    , depth(0)
    , pitch(0)
    , roll(0)
    , heading(0)  {
    }
  goal_(const ContainerAllocator& _alloc)
    : goDepth(false)
    , goPitch(false)
    , goRoll(false)
    , goHeading(false)
    , depth(0)
    , pitch(0)
    , roll(0)
    , heading(0)  {
  (void)_alloc;
    }



   typedef uint8_t _goDepth_type;
  _goDepth_type goDepth;

   typedef uint8_t _goPitch_type;
  _goPitch_type goPitch;

   typedef uint8_t _goRoll_type;
  _goRoll_type goRoll;

   typedef uint8_t _goHeading_type;
  _goHeading_type goHeading;

   typedef int16_t _depth_type;
  _depth_type depth;

   typedef int16_t _pitch_type;
  _pitch_type pitch;

   typedef int16_t _roll_type;
  _roll_type roll;

   typedef int16_t _heading_type;
  _heading_type heading;




  typedef boost::shared_ptr< ::srmauv_msgs::goal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srmauv_msgs::goal_<ContainerAllocator> const> ConstPtr;

}; // struct goal_

typedef ::srmauv_msgs::goal_<std::allocator<void> > goal;

typedef boost::shared_ptr< ::srmauv_msgs::goal > goalPtr;
typedef boost::shared_ptr< ::srmauv_msgs::goal const> goalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srmauv_msgs::goal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srmauv_msgs::goal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace srmauv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'srmauv_msgs': ['/home/parth/sedna/src/srmauv_msgs/msg', '/home/parth/sedna/devel/share/srmauv_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::srmauv_msgs::goal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srmauv_msgs::goal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srmauv_msgs::goal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srmauv_msgs::goal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srmauv_msgs::goal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srmauv_msgs::goal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srmauv_msgs::goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e3a6bb0117e9e52cd5f2550dc62beb5b";
  }

  static const char* value(const ::srmauv_msgs::goal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe3a6bb0117e9e52cULL;
  static const uint64_t static_value2 = 0xd5f2550dc62beb5bULL;
};

template<class ContainerAllocator>
struct DataType< ::srmauv_msgs::goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srmauv_msgs/goal";
  }

  static const char* value(const ::srmauv_msgs::goal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srmauv_msgs::goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool goDepth\n\
bool goPitch\n\
bool goRoll\n\
bool goHeading\n\
\n\
int16 depth\n\
int16 pitch\n\
int16 roll\n\
int16 heading\n\
";
  }

  static const char* value(const ::srmauv_msgs::goal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srmauv_msgs::goal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goDepth);
      stream.next(m.goPitch);
      stream.next(m.goRoll);
      stream.next(m.goHeading);
      stream.next(m.depth);
      stream.next(m.pitch);
      stream.next(m.roll);
      stream.next(m.heading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct goal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srmauv_msgs::goal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srmauv_msgs::goal_<ContainerAllocator>& v)
  {
    s << indent << "goDepth: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.goDepth);
    s << indent << "goPitch: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.goPitch);
    s << indent << "goRoll: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.goRoll);
    s << indent << "goHeading: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.goHeading);
    s << indent << "depth: ";
    Printer<int16_t>::stream(s, indent + "  ", v.depth);
    s << indent << "pitch: ";
    Printer<int16_t>::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    Printer<int16_t>::stream(s, indent + "  ", v.roll);
    s << indent << "heading: ";
    Printer<int16_t>::stream(s, indent + "  ", v.heading);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRMAUV_MSGS_MESSAGE_GOAL_H
