// Generated by gencpp from file srmauv_msgs/locomotion_modeRequest.msg
// DO NOT EDIT!


#ifndef SRMAUV_MSGS_MESSAGE_LOCOMOTION_MODEREQUEST_H
#define SRMAUV_MSGS_MESSAGE_LOCOMOTION_MODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srmauv_msgs
{
template <class ContainerAllocator>
struct locomotion_modeRequest_
{
  typedef locomotion_modeRequest_<ContainerAllocator> Type;

  locomotion_modeRequest_()
    : forward(false)
    , sidemove(false)  {
    }
  locomotion_modeRequest_(const ContainerAllocator& _alloc)
    : forward(false)
    , sidemove(false)  {
  (void)_alloc;
    }



   typedef uint8_t _forward_type;
  _forward_type forward;

   typedef uint8_t _sidemove_type;
  _sidemove_type sidemove;




  typedef boost::shared_ptr< ::srmauv_msgs::locomotion_modeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srmauv_msgs::locomotion_modeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct locomotion_modeRequest_

typedef ::srmauv_msgs::locomotion_modeRequest_<std::allocator<void> > locomotion_modeRequest;

typedef boost::shared_ptr< ::srmauv_msgs::locomotion_modeRequest > locomotion_modeRequestPtr;
typedef boost::shared_ptr< ::srmauv_msgs::locomotion_modeRequest const> locomotion_modeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srmauv_msgs::locomotion_modeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srmauv_msgs::locomotion_modeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace srmauv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'srmauv_msgs': ['/home/parth/sedna/src/srmauv_msgs/msg', '/home/parth/sedna/devel/share/srmauv_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::srmauv_msgs::locomotion_modeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srmauv_msgs::locomotion_modeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srmauv_msgs::locomotion_modeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srmauv_msgs::locomotion_modeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srmauv_msgs::locomotion_modeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srmauv_msgs::locomotion_modeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srmauv_msgs::locomotion_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e1e49fbddd78cd38845904708fdcf70";
  }

  static const char* value(const ::srmauv_msgs::locomotion_modeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e1e49fbddd78cd3ULL;
  static const uint64_t static_value2 = 0x8845904708fdcf70ULL;
};

template<class ContainerAllocator>
struct DataType< ::srmauv_msgs::locomotion_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srmauv_msgs/locomotion_modeRequest";
  }

  static const char* value(const ::srmauv_msgs::locomotion_modeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srmauv_msgs::locomotion_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool forward\n\
bool sidemove\n\
\n\
";
  }

  static const char* value(const ::srmauv_msgs::locomotion_modeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srmauv_msgs::locomotion_modeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.forward);
      stream.next(m.sidemove);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct locomotion_modeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srmauv_msgs::locomotion_modeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srmauv_msgs::locomotion_modeRequest_<ContainerAllocator>& v)
  {
    s << indent << "forward: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.forward);
    s << indent << "sidemove: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sidemove);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRMAUV_MSGS_MESSAGE_LOCOMOTION_MODEREQUEST_H
