// Generated by gencpp from file srmauv_msgs/pid_info.msg
// DO NOT EDIT!


#ifndef SRMAUV_MSGS_MESSAGE_PID_INFO_H
#define SRMAUV_MSGS_MESSAGE_PID_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <srmauv_msgs/ControlData.h>
#include <srmauv_msgs/ControlData.h>
#include <srmauv_msgs/ControlData.h>
#include <srmauv_msgs/ControlData.h>
#include <srmauv_msgs/ControlData.h>
#include <srmauv_msgs/ControlData.h>

namespace srmauv_msgs
{
template <class ContainerAllocator>
struct pid_info_
{
  typedef pid_info_<ContainerAllocator> Type;

  pid_info_()
    : header()
    , child_frame_id()
    , forward()
    , heading()
    , sidemove()
    , pitch()
    , roll()
    , depth()  {
    }
  pid_info_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , child_frame_id(_alloc)
    , forward(_alloc)
    , heading(_alloc)
    , sidemove(_alloc)
    , pitch(_alloc)
    , roll(_alloc)
    , depth(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _child_frame_id_type;
  _child_frame_id_type child_frame_id;

   typedef  ::srmauv_msgs::ControlData_<ContainerAllocator>  _forward_type;
  _forward_type forward;

   typedef  ::srmauv_msgs::ControlData_<ContainerAllocator>  _heading_type;
  _heading_type heading;

   typedef  ::srmauv_msgs::ControlData_<ContainerAllocator>  _sidemove_type;
  _sidemove_type sidemove;

   typedef  ::srmauv_msgs::ControlData_<ContainerAllocator>  _pitch_type;
  _pitch_type pitch;

   typedef  ::srmauv_msgs::ControlData_<ContainerAllocator>  _roll_type;
  _roll_type roll;

   typedef  ::srmauv_msgs::ControlData_<ContainerAllocator>  _depth_type;
  _depth_type depth;




  typedef boost::shared_ptr< ::srmauv_msgs::pid_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srmauv_msgs::pid_info_<ContainerAllocator> const> ConstPtr;

}; // struct pid_info_

typedef ::srmauv_msgs::pid_info_<std::allocator<void> > pid_info;

typedef boost::shared_ptr< ::srmauv_msgs::pid_info > pid_infoPtr;
typedef boost::shared_ptr< ::srmauv_msgs::pid_info const> pid_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srmauv_msgs::pid_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srmauv_msgs::pid_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace srmauv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'srmauv_msgs': ['/home/parth/sedna/src/srmauv_msgs/msg', '/home/parth/sedna/devel/share/srmauv_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::srmauv_msgs::pid_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srmauv_msgs::pid_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srmauv_msgs::pid_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srmauv_msgs::pid_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srmauv_msgs::pid_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srmauv_msgs::pid_info_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srmauv_msgs::pid_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "78380976b66601a9528770c55e37d58c";
  }

  static const char* value(const ::srmauv_msgs::pid_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x78380976b66601a9ULL;
  static const uint64_t static_value2 = 0x528770c55e37d58cULL;
};

template<class ContainerAllocator>
struct DataType< ::srmauv_msgs::pid_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srmauv_msgs/pid_info";
  }

  static const char* value(const ::srmauv_msgs::pid_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srmauv_msgs::pid_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header \n\
  string child_frame_id\n\
ControlData forward\n\
ControlData heading\n\
ControlData sidemove\n\
ControlData pitch\n\
ControlData roll\n\
ControlData depth\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: srmauv_msgs/ControlData\n\
float32 total\n\
float32 p\n\
float32 i\n\
float32 d\n\
\n\
";
  }

  static const char* value(const ::srmauv_msgs::pid_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srmauv_msgs::pid_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.child_frame_id);
      stream.next(m.forward);
      stream.next(m.heading);
      stream.next(m.sidemove);
      stream.next(m.pitch);
      stream.next(m.roll);
      stream.next(m.depth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct pid_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srmauv_msgs::pid_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srmauv_msgs::pid_info_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "child_frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.child_frame_id);
    s << indent << "forward: ";
    s << std::endl;
    Printer< ::srmauv_msgs::ControlData_<ContainerAllocator> >::stream(s, indent + "  ", v.forward);
    s << indent << "heading: ";
    s << std::endl;
    Printer< ::srmauv_msgs::ControlData_<ContainerAllocator> >::stream(s, indent + "  ", v.heading);
    s << indent << "sidemove: ";
    s << std::endl;
    Printer< ::srmauv_msgs::ControlData_<ContainerAllocator> >::stream(s, indent + "  ", v.sidemove);
    s << indent << "pitch: ";
    s << std::endl;
    Printer< ::srmauv_msgs::ControlData_<ContainerAllocator> >::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    s << std::endl;
    Printer< ::srmauv_msgs::ControlData_<ContainerAllocator> >::stream(s, indent + "  ", v.roll);
    s << indent << "depth: ";
    s << std::endl;
    Printer< ::srmauv_msgs::ControlData_<ContainerAllocator> >::stream(s, indent + "  ", v.depth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRMAUV_MSGS_MESSAGE_PID_INFO_H
