// Generated by gencpp from file srmauv_msgs/set_controller.msg
// DO NOT EDIT!


#ifndef SRMAUV_MSGS_MESSAGE_SET_CONTROLLER_H
#define SRMAUV_MSGS_MESSAGE_SET_CONTROLLER_H

#include <ros/service_traits.h>


#include <srmauv_msgs/set_controllerRequest.h>
#include <srmauv_msgs/set_controllerResponse.h>


namespace srmauv_msgs
{

struct set_controller
{

typedef set_controllerRequest Request;
typedef set_controllerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_controller
} // namespace srmauv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srmauv_msgs::set_controller > {
  static const char* value()
  {
    return "d5db543179e321d0f8a06feb429cfe4d";
  }

  static const char* value(const ::srmauv_msgs::set_controller&) { return value(); }
};

template<>
struct DataType< ::srmauv_msgs::set_controller > {
  static const char* value()
  {
    return "srmauv_msgs/set_controller";
  }

  static const char* value(const ::srmauv_msgs::set_controller&) { return value(); }
};


// service_traits::MD5Sum< ::srmauv_msgs::set_controllerRequest> should match 
// service_traits::MD5Sum< ::srmauv_msgs::set_controller > 
template<>
struct MD5Sum< ::srmauv_msgs::set_controllerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srmauv_msgs::set_controller >::value();
  }
  static const char* value(const ::srmauv_msgs::set_controllerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srmauv_msgs::set_controllerRequest> should match 
// service_traits::DataType< ::srmauv_msgs::set_controller > 
template<>
struct DataType< ::srmauv_msgs::set_controllerRequest>
{
  static const char* value()
  {
    return DataType< ::srmauv_msgs::set_controller >::value();
  }
  static const char* value(const ::srmauv_msgs::set_controllerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srmauv_msgs::set_controllerResponse> should match 
// service_traits::MD5Sum< ::srmauv_msgs::set_controller > 
template<>
struct MD5Sum< ::srmauv_msgs::set_controllerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srmauv_msgs::set_controller >::value();
  }
  static const char* value(const ::srmauv_msgs::set_controllerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srmauv_msgs::set_controllerResponse> should match 
// service_traits::DataType< ::srmauv_msgs::set_controller > 
template<>
struct DataType< ::srmauv_msgs::set_controllerResponse>
{
  static const char* value()
  {
    return DataType< ::srmauv_msgs::set_controller >::value();
  }
  static const char* value(const ::srmauv_msgs::set_controllerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRMAUV_MSGS_MESSAGE_SET_CONTROLLER_H
