// Generated by gencpp from file srmauv_msgs/set_controllerRequest.msg
// DO NOT EDIT!


#ifndef SRMAUV_MSGS_MESSAGE_SET_CONTROLLERREQUEST_H
#define SRMAUV_MSGS_MESSAGE_SET_CONTROLLERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srmauv_msgs
{
template <class ContainerAllocator>
struct set_controllerRequest_
{
  typedef set_controllerRequest_<ContainerAllocator> Type;

  set_controllerRequest_()
    : forward(false)
    , sidemove(false)
    , heading(false)
    , depth(false)
    , pitch(false)
    , roll(false)
    , topside(false)
    , navigation(false)
    , forward_vel(false)
    , sidemove_vel(false)  {
    }
  set_controllerRequest_(const ContainerAllocator& _alloc)
    : forward(false)
    , sidemove(false)
    , heading(false)
    , depth(false)
    , pitch(false)
    , roll(false)
    , topside(false)
    , navigation(false)
    , forward_vel(false)
    , sidemove_vel(false)  {
  (void)_alloc;
    }



   typedef uint8_t _forward_type;
  _forward_type forward;

   typedef uint8_t _sidemove_type;
  _sidemove_type sidemove;

   typedef uint8_t _heading_type;
  _heading_type heading;

   typedef uint8_t _depth_type;
  _depth_type depth;

   typedef uint8_t _pitch_type;
  _pitch_type pitch;

   typedef uint8_t _roll_type;
  _roll_type roll;

   typedef uint8_t _topside_type;
  _topside_type topside;

   typedef uint8_t _navigation_type;
  _navigation_type navigation;

   typedef uint8_t _forward_vel_type;
  _forward_vel_type forward_vel;

   typedef uint8_t _sidemove_vel_type;
  _sidemove_vel_type sidemove_vel;




  typedef boost::shared_ptr< ::srmauv_msgs::set_controllerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srmauv_msgs::set_controllerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_controllerRequest_

typedef ::srmauv_msgs::set_controllerRequest_<std::allocator<void> > set_controllerRequest;

typedef boost::shared_ptr< ::srmauv_msgs::set_controllerRequest > set_controllerRequestPtr;
typedef boost::shared_ptr< ::srmauv_msgs::set_controllerRequest const> set_controllerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srmauv_msgs::set_controllerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srmauv_msgs::set_controllerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace srmauv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'srmauv_msgs': ['/home/parth/sedna/src/srmauv_msgs/msg', '/home/parth/sedna/devel/share/srmauv_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::srmauv_msgs::set_controllerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srmauv_msgs::set_controllerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srmauv_msgs::set_controllerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srmauv_msgs::set_controllerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srmauv_msgs::set_controllerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srmauv_msgs::set_controllerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srmauv_msgs::set_controllerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2038e9fb629dff5329fbf0743e7ea242";
  }

  static const char* value(const ::srmauv_msgs::set_controllerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2038e9fb629dff53ULL;
  static const uint64_t static_value2 = 0x29fbf0743e7ea242ULL;
};

template<class ContainerAllocator>
struct DataType< ::srmauv_msgs::set_controllerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srmauv_msgs/set_controllerRequest";
  }

  static const char* value(const ::srmauv_msgs::set_controllerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srmauv_msgs::set_controllerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool forward\n\
bool sidemove\n\
bool heading\n\
bool depth\n\
bool pitch\n\
bool roll\n\
bool topside\n\
bool navigation\n\
bool forward_vel\n\
bool sidemove_vel\n\
\n\
";
  }

  static const char* value(const ::srmauv_msgs::set_controllerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srmauv_msgs::set_controllerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.forward);
      stream.next(m.sidemove);
      stream.next(m.heading);
      stream.next(m.depth);
      stream.next(m.pitch);
      stream.next(m.roll);
      stream.next(m.topside);
      stream.next(m.navigation);
      stream.next(m.forward_vel);
      stream.next(m.sidemove_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct set_controllerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srmauv_msgs::set_controllerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srmauv_msgs::set_controllerRequest_<ContainerAllocator>& v)
  {
    s << indent << "forward: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.forward);
    s << indent << "sidemove: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sidemove);
    s << indent << "heading: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.heading);
    s << indent << "depth: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.depth);
    s << indent << "pitch: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.roll);
    s << indent << "topside: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.topside);
    s << indent << "navigation: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.navigation);
    s << indent << "forward_vel: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.forward_vel);
    s << indent << "sidemove_vel: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sidemove_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRMAUV_MSGS_MESSAGE_SET_CONTROLLERREQUEST_H
