# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from srmauv_msgs/thruster_alp.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class thruster_alp(genpy.Message):
  _md5sum = "89339d224c3178f92d13953b3be49918"
  _type = "srmauv_msgs/thruster_alp"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int16 speedfwd1
int16 speedfwd2
int16 speedup1
int16 speedup2
int16 speedup3
int16 speedup4
int16 speeddir1
int16 speeddir2
"""
  __slots__ = ['speedfwd1','speedfwd2','speedup1','speedup2','speedup3','speedup4','speeddir1','speeddir2']
  _slot_types = ['int16','int16','int16','int16','int16','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       speedfwd1,speedfwd2,speedup1,speedup2,speedup3,speedup4,speeddir1,speeddir2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(thruster_alp, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.speedfwd1 is None:
        self.speedfwd1 = 0
      if self.speedfwd2 is None:
        self.speedfwd2 = 0
      if self.speedup1 is None:
        self.speedup1 = 0
      if self.speedup2 is None:
        self.speedup2 = 0
      if self.speedup3 is None:
        self.speedup3 = 0
      if self.speedup4 is None:
        self.speedup4 = 0
      if self.speeddir1 is None:
        self.speeddir1 = 0
      if self.speeddir2 is None:
        self.speeddir2 = 0
    else:
      self.speedfwd1 = 0
      self.speedfwd2 = 0
      self.speedup1 = 0
      self.speedup2 = 0
      self.speedup3 = 0
      self.speedup4 = 0
      self.speeddir1 = 0
      self.speeddir2 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_8h.pack(_x.speedfwd1, _x.speedfwd2, _x.speedup1, _x.speedup2, _x.speedup3, _x.speedup4, _x.speeddir1, _x.speeddir2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.speedfwd1, _x.speedfwd2, _x.speedup1, _x.speedup2, _x.speedup3, _x.speedup4, _x.speeddir1, _x.speeddir2,) = _struct_8h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_8h.pack(_x.speedfwd1, _x.speedfwd2, _x.speedup1, _x.speedup2, _x.speedup3, _x.speedup4, _x.speeddir1, _x.speeddir2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.speedfwd1, _x.speedfwd2, _x.speedup1, _x.speedup2, _x.speedup3, _x.speedup4, _x.speeddir1, _x.speeddir2,) = _struct_8h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_8h = struct.Struct("<8h")
