# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from srmauv_msgs/buoy.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class buoy(genpy.Message):
  _md5sum = "32326659a962285da2405f27fc182109"
  _type = "srmauv_msgs/buoy"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool possible_red
bool possible_green
float32 x_offset_green
float32 y_offset_green
float32 x_offset_red
float32 y_offset_red
"""
  __slots__ = ['possible_red','possible_green','x_offset_green','y_offset_green','x_offset_red','y_offset_red']
  _slot_types = ['bool','bool','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       possible_red,possible_green,x_offset_green,y_offset_green,x_offset_red,y_offset_red

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(buoy, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.possible_red is None:
        self.possible_red = False
      if self.possible_green is None:
        self.possible_green = False
      if self.x_offset_green is None:
        self.x_offset_green = 0.
      if self.y_offset_green is None:
        self.y_offset_green = 0.
      if self.x_offset_red is None:
        self.x_offset_red = 0.
      if self.y_offset_red is None:
        self.y_offset_red = 0.
    else:
      self.possible_red = False
      self.possible_green = False
      self.x_offset_green = 0.
      self.y_offset_green = 0.
      self.x_offset_red = 0.
      self.y_offset_red = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2B4f.pack(_x.possible_red, _x.possible_green, _x.x_offset_green, _x.y_offset_green, _x.x_offset_red, _x.y_offset_red))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.possible_red, _x.possible_green, _x.x_offset_green, _x.y_offset_green, _x.x_offset_red, _x.y_offset_red,) = _struct_2B4f.unpack(str[start:end])
      self.possible_red = bool(self.possible_red)
      self.possible_green = bool(self.possible_green)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2B4f.pack(_x.possible_red, _x.possible_green, _x.x_offset_green, _x.y_offset_green, _x.x_offset_red, _x.y_offset_red))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.possible_red, _x.possible_green, _x.x_offset_green, _x.y_offset_green, _x.x_offset_red, _x.y_offset_red,) = _struct_2B4f.unpack(str[start:end])
      self.possible_red = bool(self.possible_red)
      self.possible_green = bool(self.possible_green)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2B4f = struct.Struct("<2B4f")
