; Auto-generated. Do not edit!


(cl:in-package smach_-msg)


;//! \htmlinclude sinkResult.msg.html

(cl:defclass <sinkResult> (roslisp-msg-protocol:ros-message)
  ((pose
    :reader pose
    :initarg :pose
    :type cl:integer
    :initform 0))
)

(cl:defclass sinkResult (<sinkResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <sinkResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'sinkResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name smach_-msg:<sinkResult> is deprecated: use smach_-msg:sinkResult instead.")))

(cl:ensure-generic-function 'pose-val :lambda-list '(m))
(cl:defmethod pose-val ((m <sinkResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader smach_-msg:pose-val is deprecated.  Use smach_-msg:pose instead.")
  (pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <sinkResult>) ostream)
  "Serializes a message object of type '<sinkResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'pose)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'pose)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'pose)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'pose)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <sinkResult>) istream)
  "Deserializes a message object of type '<sinkResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'pose)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'pose)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'pose)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'pose)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<sinkResult>)))
  "Returns string type for a message object of type '<sinkResult>"
  "smach_/sinkResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'sinkResult)))
  "Returns string type for a message object of type 'sinkResult"
  "smach_/sinkResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<sinkResult>)))
  "Returns md5sum for a message object of type '<sinkResult>"
  "b175d75510e918e243b20826df615025")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'sinkResult)))
  "Returns md5sum for a message object of type 'sinkResult"
  "b175d75510e918e243b20826df615025")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<sinkResult>)))
  "Returns full string definition for message of type '<sinkResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 pose~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'sinkResult)))
  "Returns full string definition for message of type 'sinkResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 pose~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <sinkResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <sinkResult>))
  "Converts a ROS message object to a list"
  (cl:list 'sinkResult
    (cl:cons ':pose (pose msg))
))
