// Generated by gencpp from file srmauv_msgs/thruster.msg
// DO NOT EDIT!


#ifndef SRMAUV_MSGS_MESSAGE_THRUSTER_H
#define SRMAUV_MSGS_MESSAGE_THRUSTER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srmauv_msgs
{
template <class ContainerAllocator>
struct thruster_
{
  typedef thruster_<ContainerAllocator> Type;

  thruster_()
    : speed1(0)
    , speed2(0)
    , speed3(0)
    , speed4(0)
    , speed5(0)
    , speed6(0)
    , speed7(0)
    , speed8(0)  {
    }
  thruster_(const ContainerAllocator& _alloc)
    : speed1(0)
    , speed2(0)
    , speed3(0)
    , speed4(0)
    , speed5(0)
    , speed6(0)
    , speed7(0)
    , speed8(0)  {
  (void)_alloc;
    }



   typedef int16_t _speed1_type;
  _speed1_type speed1;

   typedef int16_t _speed2_type;
  _speed2_type speed2;

   typedef int16_t _speed3_type;
  _speed3_type speed3;

   typedef int16_t _speed4_type;
  _speed4_type speed4;

   typedef int16_t _speed5_type;
  _speed5_type speed5;

   typedef int16_t _speed6_type;
  _speed6_type speed6;

   typedef int16_t _speed7_type;
  _speed7_type speed7;

   typedef int16_t _speed8_type;
  _speed8_type speed8;




  typedef boost::shared_ptr< ::srmauv_msgs::thruster_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srmauv_msgs::thruster_<ContainerAllocator> const> ConstPtr;

}; // struct thruster_

typedef ::srmauv_msgs::thruster_<std::allocator<void> > thruster;

typedef boost::shared_ptr< ::srmauv_msgs::thruster > thrusterPtr;
typedef boost::shared_ptr< ::srmauv_msgs::thruster const> thrusterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srmauv_msgs::thruster_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srmauv_msgs::thruster_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace srmauv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'srmauv_msgs': ['/home/parth/sedna/src/srmauv_msgs/msg', '/home/parth/sedna/devel/share/srmauv_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::srmauv_msgs::thruster_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srmauv_msgs::thruster_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srmauv_msgs::thruster_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srmauv_msgs::thruster_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srmauv_msgs::thruster_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srmauv_msgs::thruster_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srmauv_msgs::thruster_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58cf37a5ce4f852e59a4eb1cfea68751";
  }

  static const char* value(const ::srmauv_msgs::thruster_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58cf37a5ce4f852eULL;
  static const uint64_t static_value2 = 0x59a4eb1cfea68751ULL;
};

template<class ContainerAllocator>
struct DataType< ::srmauv_msgs::thruster_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srmauv_msgs/thruster";
  }

  static const char* value(const ::srmauv_msgs::thruster_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srmauv_msgs::thruster_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 speed1\n\
int16 speed2\n\
int16 speed3\n\
int16 speed4\n\
int16 speed5\n\
int16 speed6\n\
int16 speed7\n\
int16 speed8\n\
";
  }

  static const char* value(const ::srmauv_msgs::thruster_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srmauv_msgs::thruster_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed1);
      stream.next(m.speed2);
      stream.next(m.speed3);
      stream.next(m.speed4);
      stream.next(m.speed5);
      stream.next(m.speed6);
      stream.next(m.speed7);
      stream.next(m.speed8);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct thruster_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srmauv_msgs::thruster_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srmauv_msgs::thruster_<ContainerAllocator>& v)
  {
    s << indent << "speed1: ";
    Printer<int16_t>::stream(s, indent + "  ", v.speed1);
    s << indent << "speed2: ";
    Printer<int16_t>::stream(s, indent + "  ", v.speed2);
    s << indent << "speed3: ";
    Printer<int16_t>::stream(s, indent + "  ", v.speed3);
    s << indent << "speed4: ";
    Printer<int16_t>::stream(s, indent + "  ", v.speed4);
    s << indent << "speed5: ";
    Printer<int16_t>::stream(s, indent + "  ", v.speed5);
    s << indent << "speed6: ";
    Printer<int16_t>::stream(s, indent + "  ", v.speed6);
    s << indent << "speed7: ";
    Printer<int16_t>::stream(s, indent + "  ", v.speed7);
    s << indent << "speed8: ";
    Printer<int16_t>::stream(s, indent + "  ", v.speed8);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRMAUV_MSGS_MESSAGE_THRUSTER_H
