(cl:defpackage srmauv_msgs-srv
  (:use )
  (:export
   "LOCOMOTION_MODE"
   "<LOCOMOTION_MODE-REQUEST>"
   "LOCOMOTION_MODE-REQUEST"
   "<LOCOMOTION_MODE-RESPONSE>"
   "LOCOMOTION_MODE-RESPONSE"
   "C0NTROL"
   "<C0NTROL-REQUEST>"
   "C0NTROL-REQUEST"
   "<C0NTROL-RESPONSE>"
   "C0NTROL-RESPONSE"
   "SET_CONTROLLER"
   "<SET_CONTROLLER-REQUEST>"
   "SET_CONTROLLER-REQUEST"
   "<SET_CONTROLLER-RESPONSE>"
   "SET_CONTROLLER-RESPONSE"
  ))

