(cl:in-package srmauv_msgs-msg)
(cl:export '(HEADING_SETPOINT-VAL
          HEADING_SETPOINT
          FORWARD_SETPOINT-VAL
          FORWARD_SETPOINT
          SIDEMOVE_SETPOINT-VAL
          SIDEMOVE_SETPOINT
          DEPTH_SETPOINT-VAL
          DEPTH_SETPOINT
          FORWARD_VEL_SETPOINT-VAL
          FORWARD_VEL_SETPOINT
          SIDEMOVE_VEL_SETPOINT-VAL
          SIDEMOVE_VEL_SETPOINT
))